---
# tasks file for lvm-ansible-role

- name: Install necessary packages
  yum:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ lvm_packages_EL }}"

- name: Recheck for scsi devices
  command: sg_scan
  changed_when: false

- name: Rescan for new disks
  command: /usr/bin/rescan-scsi-bus.sh -a
  changed_when: false

- name: Get partition list
  command: lsblk
  register: lsblk_list
  changed_when: false

- name: Create lvm volume(s)
  import_tasks: create-lvm.yml
  when: lvm_volumes

- name: Mount lvm volume(s)
  import_tasks: mount-lvm.yml
  when: lvm_volumes

- name: Unmount lvm volume(s)
  import_tasks: unmount-lvm.yml
  when: lvm_volumes

- name: Remove lvm volume(s)
  import_tasks: remove-lvm.yml
  when: lvm_volumes
