---
# tasks file for lvm-ansible-role

- name: Unmount volume
  mount:
    name: "{{ item.mount }}"
    src: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
    fstype: "{{ item.filesystem }}"
    state: unmounted
  with_items: "{{ lvm_volumes }}"
  when: >
    (item.mounted is defined and item.mounted == False) or
    (item.state is defined and item.state == "absent")

- name: Remove mount from fstab
  mount:
    name: "{{ item.mount }}"
    src: "/dev/{{ item.vg_name }}/{{ item.lv_name }}"
    fstype: "{{ item.filesystem }}"
    state: absent
  with_items: "{{ lvm_volumes }}"
  when: >
    (item.mounted is defined and item.mounted == False) or
    (item.state is defined and item.state == "absent")
